
show:
    npx wrangler pages deployment list

copy-headers:
    cp -v _headers dist/

dev:
    just copy-headers
    npx wrangler pages dev dist --ip 0.0.0.0

deploy-production:
    just copy-headers
    npx wrangler pages deploy
