import:
    surreal import --conn http://localhost:8000 -u root -p jour --namespace based --database cooking sql/recipes.surql

export:
    surreal export --conn http://localhost:8000 -u root -p jour --namespace based --database cooking sql/recipes.surql
